AWSTemplateFormatVersion: '2010-09-09'
Description: Fase 2 - Deploy Limpo com Suporte a Root e WWW v2

Parameters:
  DomainName:
    Type: String
    Default: willdiniz.com.br
  WwwDomainName:
    Type: String
    Default: www.willdiniz.com.br
  HostedZoneId:
    Type: String
  BucketName:
    Type: String
  CertificateArn:
    Type: String
    Description: "Cole o ARN do seu certificado (aquele que tem os dois dominios)"

Resources:
  MyOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Description: !Sub "Acesso seguro para ${DomainName}"
        Name: !Sub "OAC-Portfolio-Novo"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Ref WwwDomainName
        Enabled: true
        DefaultRootObject: index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: S3Origin
            DomainName: !Sub "${BucketName}.s3.${AWS::Region}.amazonaws.com"
            OriginAccessControlId: !GetAtt MyOAC.Id
            S3OriginConfig:
              OriginAccessIdentity: "" 
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ForwardedValues:
            QueryString: false

  DNSRecordRoot:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  DNSRecordWww:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref WwwDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  MyBucketPolicyRestored:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: "s3:GetObject"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"
            Principal:
              Service: "cloudfront.amazonaws.com"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${MyDistribution}"

Outputs:
  DistributionId:
    Value: !Ref MyDistribution
  CloudFrontDomain:
    Value: !GetAtt MyDistribution.DomainName